project:
  type: website
  output-dir: docs

website:
  title: "A Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - VZYHEI003.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
